# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
#    mail:
#        host: smtp.mailgun.org
#        port: 587
#        username: postmaster@sandboxf7ffda7599b84638ab08ae287d9a46e2.mailgun.org
#        password: d4e2c8a6d220ee4c78086c50c96bbb7f
#        from : postmaster@sandboxf7ffda7599b84638ab08ae287d9a46e2.mailgun.org
    datasource:
        url: jdbc:postgresql://localhost:5432/testdb
        username: amit
        password: igdefault
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
            dialect : org.hibernate.dialect.PostgreSQLDialect

#            hibernate.dialect=org.hibernate.dialect.H2Dialect
#            hibernate.hbm2ddl.auto=create-drop
#            hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
#            hibernate.show_sql=false
#            hibernate.format_sql=true
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

logging:
  level:
    org.springframework: INFO
  path: /var/log/R3/demo
